# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scoredlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(440, 380)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cb1 = QtWidgets.QComboBox(Dialog)
        self.cb1.setObjectName("cb1")
        import sqlite3
        db=sqlite3.connect('cricket.db')
        self.horizontalLayout.addWidget(self.cb1)
        sql="select Name from teams"
        cur=db.execute(sql)
        teams=[]
        for row in cur:
            self.cb1.addItem(row[0])
        db.close()
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.cb2 = QtWidgets.QComboBox(Dialog)
        self.cb2.setObjectName("cb2")
        self.cb2.addItem("")
        self.horizontalLayout.addWidget(self.cb2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lw1 = QtWidgets.QListWidget(Dialog)
        self.lw1.setObjectName("lw1")
        self.horizontalLayout_3.addWidget(self.lw1)
        spacerItem = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.lw2 = QtWidgets.QListWidget(Dialog)
        self.lw2.setObjectName("lw2")
        self.horizontalLayout_3.addWidget(self.lw2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.calculate)
        self.horizontalLayout_4.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.scorelabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.scorelabel.setFont(font)
        self.scorelabel.setObjectName("scorelabel")
        self.horizontalLayout_4.addWidget(self.scorelabel)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
    def calculate(self):
        import sqlite3
        db = sqlite3.connect('cricket.db')
        team=self.cb1.currentText()
        self.lw1.clear()
        sql1="select players,value from teams where Name='"+team+"'"
        cur=db.execute(sql1)
        row=cur.fetchone()
        #print (row[0])
        selected=row[0].split(',')
        #print(selected)
        self.lw1.addItems(selected)
        teamttl=0
        self.lw2.clear()
        match=self.cb2.currentText()
        for i in range(self.lw1.count()):
            ttl, batscore, bowlscore, fieldscore=0,0,0,0
            nm=self.lw1.item(i).text()
            cursor=db.execute("select * from "+match+" where Player='"+nm+"'")
            row=cursor.fetchone()
            #print(row)
            batscore=int(row[1]/2)
            if batscore>=50: batscore+=5
            if batscore>=100: batscore+=10
            if row[1]>0:
                sr=row[1]/row[2]*100
                if sr>=80 and sr<100:batscore+=2
                if sr>=100:batscore+=4
            batscore=batscore+row[3]
            batscore=batscore+2*row[4]
            #print("Batting score=",batscore)
            bowlscore=row[8]*10
            if row[8]>=3:bowlscore+5
            if row[8]>=5:bowlscore=bowlscore+10
            if row[7]>0:
                er=6*row[7]/row[5]
                #print("eco:",er)
                if er<=2:
                    bowlscore=bowlscore+10
                if er>2 and er<=3.5:
                    bowlscore=bowlscore+7
                if er>3.5 and er<=4.5:
                    bowlscore=bowlscore+4
            fieldscore=(row[9]+row[10]+row[11])*10
            ttl=batscore+bowlscore+fieldscore
            self.lw2.addItem(str(ttl))
            teamttl=teamttl+ttl
        self.scorelabel.setText(str(teamttl))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Choose Team"))
        self.label_2.setText(_translate("Dialog", "Choose Match"))
        self.cb2.setItemText(0, _translate("Dialog", "Match1"))
        self.label_3.setText(_translate("Dialog", "Players"))
        self.label_4.setText(_translate("Dialog", "Score"))
        self.pushButton.setText(_translate("Dialog", "Calculate Score"))
        self.scorelabel.setText(_translate("Dialog", "00"))
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
